import React from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, Shield, FileText, Clock, AlertTriangle, Scale, Lock, RefreshCw, MessageCircle, Globe } from 'lucide-react';
import { Language } from '../../src/translations';

interface LegalModalProps {
  isOpen: boolean;
  onClose: () => void;
  language: Language;
  type: 'terms' | 'privacy';
}

export const LegalModal: React.FC<LegalModalProps> = ({ isOpen, onClose, language, type }) => {
  const isRu = language === 'ru';

  const termsContent = {
    title: isRu ? 'Политика конфиденциальности\nПравила и условия' : 'SmartEye Privacy Policy & Terms',
    lastUpdated: isRu ? '8 апреля 2026 г.' : 'April 8, 2026',
    intro: isRu 
      ? 'Добро пожаловать в SmartEye — аналитическую платформу для мониторинга криптовалютных рынков. Пожалуйста, внимательно ознакомьтесь с данными правилами перед использованием сервиса.'
      : 'Welcome to SmartEye — an analytical platform for monitoring cryptocurrency markets. Please read these rules carefully before using the service.',
    sections: [
      {
        id: 1,
        title: isRu ? '1. Общие положения' : '1. General Provisions',
        icon: <Scale size={18} />,
        items: isRu ? [
          '1.1. Платформа SmartEye (далее — «Сервис») предоставляет инструменты для анализа рыночных данных, включая мониторинг плотностей в стаканах (Order Book), ИИ-аналитику на базе Gemini 3 Pro и скрининг торговых пар.',
          '1.2. Используя Сервис, вы подтверждаете, что вам исполнилось 18 лет и вы полностью принимаете данные условия.'
        ] : [
          '1.1. The SmartEye platform (hereinafter — "Service") provides tools for analyzing market data, including order book density monitoring, AI analytics based on Gemini 3 Pro, and screening of trading pairs.',
          '1.2. By using the Service, you confirm that you are at least 18 years old and fully accept these terms.'
        ]
      },
      {
        id: 2,
        title: isRu ? '2. Отказ от финансовой ответственности (Дисклеймер)' : '2. Financial Disclaimer',
        icon: <AlertTriangle size={18} />,
        items: isRu ? [
          '2.1. SmartEye НЕ ЯВЛЯЕТСЯ финансовым советником. Все данные, сигналы, ИИ-отчеты и показатели плотностей предоставляются исключительно в информационных целях.',
          '2.2. Любые торговые решения, принятые на основе данных Сервиса, являются вашей исключительной ответственностью. Мы не гарантируем прибыль и не несем ответственности за ваши финансовые убытки.',
          '2.3. Криптовалютный рынок обладает высокой волатильностью. Прошлые результаты не гарантируют будущих показателей.'
        ] : [
          '2.1. SmartEye IS NOT a financial advisor. All data, signals, AI reports, and density indicators are provided for informational purposes only.',
          '2.2. Any trading decisions made based on the Service\'s data are your sole responsibility. We do not guarantee profit and are not liable for your financial losses.',
          '2.3. The cryptocurrency market is highly volatile. Past performance does not guarantee future results.'
        ]
      },
      {
        id: 3,
        title: isRu ? '3. Точность данных' : '3. Data Accuracy',
        icon: <RefreshCw size={18} />,
        items: isRu ? [
          '3.1. Сервис транслирует данные напрямую с бирж (Binance, Bybit) через WebSocket-протоколы. Мы стремимся к максимальной точности, однако не несем ответственности за задержки, технические сбои на стороне бирж или ошибки в передаче данных.',
          '3.2. ИИ-аналитика (SmartEye AI) генерируется нейросетью и может содержать неточности. Это вспомогательный инструмент, а не руководство к действию.'
        ] : [
          '3.1. The Service broadcasts data directly from exchanges (Binance, Bybit) via WebSocket protocols. We strive for maximum accuracy, but are not responsible for delays, technical failures on the exchange side, or data transmission errors.',
          '3.2. AI analytics (SmartEye AI) is generated by a neural network and may contain inaccuracies. It is a supplementary tool, not a guide to action.'
        ]
      },
      {
        id: 4,
        title: isRu ? '4. Подписки и платежи' : '4. Subscriptions and Payments',
        icon: <Shield size={18} />,
        items: isRu ? [
          '4.1. Доступ к расширенным функциям (Pro, Whale) предоставляется на основе платной подписки.',
          '4.2. Все платежи являются окончательными. Возврат средств не предусмотрен, за исключением случаев технических сбоев, подтвержденных администрацией.',
          '4.3. Администрация оставляет за собой право изменять стоимость тарифных планов, уведомляя пользователей через интерфейс Сервиса.'
        ] : [
          '4.1. Access to advanced features (Pro, Whale) is provided on a paid subscription basis.',
          '4.2. All payments are final. No refunds are provided, except in cases of technical failures confirmed by the administration.',
          '4.3. The administration reserves the right to change the cost of subscription plans, notifying users through the Service interface.'
        ]
      },
      {
        id: 5,
        title: isRu ? '5. Ограничения и запреты' : '5. Restrictions and Prohibitions',
        icon: <Lock size={18} />,
        items: isRu ? [
          '5.1. Использовать автоматизированные скрипты (боты) для сбора данных с платформы (парсинг) без официального API.',
          '5.2. Пытаться взломать систему или декомпилировать код Сервиса.',
          '5.3. Передавать доступ к своему аккаунту третьим лицам.',
          '5.4. Использовать Сервис для ведения незаконной деятельности.'
        ] : [
          '5.1. Using automated scripts (bots) to collect data from the platform (parsing) without an official API.',
          '5.2. Attempting to hack the system or decompile the Service\'s code.',
          '5.3. Transferring account access to third parties.',
          '5.4. Using the Service for illegal activities.'
        ]
      },
      {
        id: 6,
        title: isRu ? '6. Блокировка аккаунта' : '6. Account Blocking',
        icon: <AlertTriangle size={18} />,
        items: isRu ? [
          '6.1. Администрация имеет право приостановить или полностью заблокировать доступ к Сервису (Ban) в случае нарушения данных правил, подозрительной активности или попыток нанести вред платформе.',
          '6.2. В случае блокировки за нарушение правил, остаток средств за оплаченную подписку не возвращается.'
        ] : [
          '6.1. The administration has the right to suspend or completely block access to the Service (Ban) in case of violation of these rules, suspicious activity, or attempts to harm the platform.',
          '6.2. In case of blocking for rule violations, the remaining balance of the paid subscription is not refunded.'
        ]
      },
      {
        id: 7,
        title: isRu ? '7. Конфиденциальность' : '7. Privacy',
        icon: <Shield size={18} />,
        items: isRu ? [
          '1.1. Мы собираем минимальный набор данных: ваш email, имя пользователя и информацию о профиле для обеспечения работы аккаунта.',
          '1.2. Мы не храним ваши пароли в открытом виде — все данные шифруются.'
        ] : [
          '1.1. We collect the minimum necessary data for account operation (email, login). Your personal information is protected and not shared with third parties.',
          '1.2. We do not store your private exchange keys (if added in the future) — all operations occur on the client side or through secure proxy servers.'
        ]
      },
      {
        id: 8,
        title: isRu ? '8. Изменение условий' : '8. Changes to Terms',
        icon: <RefreshCw size={18} />,
        items: isRu ? [
          '8.1. SmartEye оставляет за собой право изменять данные правила в любое время. Продолжение использования Сервиса после внесения изменений означает ваше согласие с новой редакцией правил.'
        ] : [
          '8.1. SmartEye reserves the right to change these rules at any time. Continued use of the Service after changes are made signifies your agreement to the new version of the rules.'
        ]
      }
    ],
    contact: {
      title: isRu ? 'Контактная информация:' : 'Contact Information:',
      text: isRu 
        ? 'Если у вас возникли вопросы по данным правилам, пожалуйста, свяжитесь с нашей службой поддержки в Telegram: @tiger_trade_official'
        : 'If you have any questions regarding these rules, please contact our support team on Telegram: @tiger_trade_official'
    }
  };

  const privacyContent_base_ru = {
    sections: [
      {
        id: 'p1',
        title: '1. Сбор информации',
        icon: <FileText size={18} />,
        items: [
          '1.1. Мы собираем минимальный набор данных: ваш email, имя пользователя и информацию о профиле для обеспечения работы аккаунта.',
          '1.2. Мы не храним ваши пароли в открытом виде — все данные шифруются.'
        ]
      },
      {
        id: 'p2',
        title: '2. Использование данных',
        icon: <RefreshCw size={18} />,
        items: [
          '2.1. Данные используются для предоставления услуг платформы, управления подписками и улучшения алгоритмов ИИ-аналитики.',
          '2.2. Мы можем использовать ваш email для отправки важных уведомлений о работе Сервиса.'
        ]
      },
      {
        id: 'p3',
        title: '3. Файлы Cookie и хранилище',
        icon: <Lock size={18} />,
        items: [
          '3.1. Мы используем локальное хранилище браузера (Local Storage) и файлы cookie для сохранения ваших настроек интерфейса и сессии авторизации.',
          '3.2. Вы можете отключить использование cookie в настройках браузера, но это может нарушить работу Сервиса.'
        ]
      },
      {
        id: 'p4',
        title: '4. Сторонние сервисы',
        icon: <Globe size={18} />,
        items: [
          '4.1. Для ИИ-анализа мы используем Google Gemini. Личные данные пользователей не передаются в ИИ-модель.',
          '4.2. Для авторизации и хранения данных используется Firebase (Google Cloud). Ваши данные защищены инфраструктурой Google.'
        ]
      },
      {
        id: 'p5',
        title: '5. Безопасность',
        icon: <Shield size={18} />,
        items: [
          '5.1. Мы применяем современные стандарты шифрования (SSL/TLS) для защиты передачи данных.',
          '5.2. Доступ к базе данных строго ограничен и контролируется системой безопасности Firebase.'
        ]
      },
      {
        id: 'p6',
        title: '6. Права пользователя',
        icon: <Scale size={18} />,
        items: [
          '6.1. Вы имеете право в любой момент запросить удаление вашего аккаунта и всех связанных с ним данных.',
          '6.2. Для удаления данных свяжитесь с поддержкой или воспользуйтесь функцией удаления в профиле.'
        ]
      }
    ]
  };

  const privacyContent_base_en = {
    sections: [
      {
        id: 'p1',
        title: '1. Information Collection',
        icon: <FileText size={18} />,
        items: [
          '1.1. We collect a minimal set of data: your email, username, and profile information to ensure account operation.',
          '1.2. We do not store your passwords in plain text — all data is encrypted.'
        ]
      },
      {
        id: 'p2',
        title: '2. Data Usage',
        icon: <RefreshCw size={18} />,
        items: [
          '2.1. Data is used to provide platform services, manage subscriptions, and improve AI analytics algorithms.',
          '2.2. We may use your email to send important notifications about the Service.'
        ]
      },
      {
        id: 'p3',
        title: '3. Cookies and Storage',
        icon: <Lock size={18} />,
        items: [
          '3.1. We use browser local storage and cookies to save your interface settings and authorization session.',
          '3.2. You can disable cookies in your browser settings, but this may disrupt the Service.'
        ]
      },
      {
        id: 'p4',
        title: '4. Third-Party Services',
        icon: <Globe size={18} />,
        items: [
          '4.1. For AI analysis, we use Google Gemini. Personal user data is not transmitted to the AI model.',
          '4.2. Firebase (Google Cloud) is used for authorization and data storage. Your data is protected by Google infrastructure.'
        ]
      },
      {
        id: 'p5',
        title: '5. Security',
        icon: <Shield size={18} />,
        items: [
          '5.1. We apply modern encryption standards (SSL/TLS) to protect data transmission.',
          '5.2. Access to the database is strictly limited and controlled by the Firebase security system.'
        ]
      },
      {
        id: 'p6',
        title: '6. User Rights',
        icon: <Scale size={18} />,
        items: [
          '6.1. You have the right to request the deletion of your account and all associated data at any time.',
          '6.2. To delete data, contact support or use the deletion function in your profile.'
        ]
      }
    ]
  };

  const privacyContent = {
    title: isRu ? 'Политика конфиденциальности\nПравила и условия' : 'SmartEye Privacy Policy & Terms',
    lastUpdated: isRu ? '8 апреля 2026 г.' : 'April 8, 2026',
    intro: isRu 
      ? 'Ваша конфиденциальность и соблюдение правил важны для нас. В этом документе описано, как мы защищаем ваши данные и какие правила действуют при использовании Сервиса.'
      : 'Your privacy and compliance are important to us. This document describes how we protect your data and what rules apply when using the Service.',
    sections: isRu ? [
      ...privacyContent_base_ru.sections,
      { id: 'divider', isDivider: true },
      ...termsContent.sections
    ] : [
      ...privacyContent_base_en.sections,
      { id: 'divider', isDivider: true },
      ...termsContent.sections
    ],
    contact: {
      title: isRu ? 'Контактная информация:' : 'Contact Information:',
      text: isRu 
        ? 'По вопросам конфиденциальности и работы сервиса пишите нам в Telegram: @tiger_trade_official'
        : 'For privacy and service concerns, contact us on Telegram: @tiger_trade_official'
    }
  };

  const content = type === 'terms' ? termsContent : privacyContent;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[300] flex items-center justify-center p-4 md:p-8"
        >
          <div className="absolute inset-0 bg-black/90 backdrop-blur-xl" onClick={onClose} />
          
          <motion.div
            initial={{ scale: 0.95, opacity: 0, y: 20 }}
            animate={{ scale: 1, opacity: 1, y: 0 }}
            exit={{ scale: 0.95, opacity: 0, y: 20 }}
            className="relative w-full max-w-4xl max-h-[90vh] bg-[#0c0c0e] border border-white/10 rounded-[2.5rem] overflow-hidden flex flex-col shadow-[0_0_100px_rgba(0,0,0,0.5)]"
          >
            {/* Header */}
            <div className="p-8 border-b border-white/5 flex items-center justify-between bg-white/[0.02]">
              <div className="flex items-center gap-4">
                <div className="w-12 h-12 rounded-2xl bg-white/5 border border-white/10 flex items-center justify-center">
                  {type === 'terms' ? <FileText className="text-purple-400" /> : <Shield className="text-blue-400" />}
                </div>
                <div>
                  <h2 className="text-xl font-black text-white uppercase tracking-tight whitespace-pre-line">
                    {content.title}
                  </h2>
                  <div className="flex items-center gap-2 text-[10px] text-gray-500 font-bold uppercase tracking-widest mt-1">
                    <Clock size={12} />
                    {content.lastUpdated}
                  </div>
                </div>
              </div>
              <button 
                onClick={onClose}
                className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 transition-all"
              >
                <X size={20} />
              </button>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto p-8 space-y-12 custom-scrollbar">
              <p className="text-gray-400 text-sm font-medium leading-relaxed italic border-l-2 border-purple-500/50 pl-6">
                {content.intro}
              </p>

              <div className="space-y-10">
                {content.sections.map((section: any) => {
                  if (section.isDivider) {
                    return (
                      <div key={section.id} className="py-10 border-t border-white/5 relative">
                        <div className="absolute top-[-14px] left-1/2 -translate-x-1/2 px-6 bg-[#0c0c0e] text-[10px] font-black text-purple-400 uppercase tracking-[0.3em]">
                          {isRu ? 'Правила и условия' : 'Terms & Conditions'}
                        </div>
                      </div>
                    );
                  }
                  return (
                    <div key={section.id} className="space-y-4">
                      <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-gray-400">
                          {section.icon}
                        </div>
                        <h3 className="text-base font-black text-white uppercase tracking-wide">
                          {section.title}
                        </h3>
                      </div>
                      <div className="space-y-3 pl-11">
                        {section.items.map((item: any, idx: number) => (
                          <p key={idx} className="text-gray-500 text-sm font-medium leading-relaxed">
                            {item}
                          </p>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Contact */}
              <div className="p-8 rounded-3xl bg-white/[0.02] border border-white/5 space-y-4">
                <h4 className="text-sm font-black text-white uppercase tracking-widest flex items-center gap-2">
                  <MessageCircle size={18} className="text-blue-400" />
                  {content.contact.title}
                </h4>
                <p className="text-gray-500 text-sm font-medium leading-relaxed">
                  {content.contact.text}
                </p>
                <a 
                  href="https://t.me/tiger_trade_official" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-6 py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-[10px] font-black text-white uppercase tracking-widest transition-all"
                >
                  <MessageCircle size={14} /> Telegram Support
                </a>
              </div>
            </div>

            {/* Footer */}
            <div className="p-6 border-t border-white/5 bg-white/[0.01] flex justify-center">
              <button 
                onClick={onClose}
                className="px-12 py-4 rounded-2xl bg-white text-black text-[11px] font-black uppercase tracking-[0.2em] hover:scale-[1.02] active:scale-[0.98] transition-all shadow-[0_10px_30px_rgba(255,255,255,0.1)]"
              >
                {isRu ? 'Закрыть' : 'Close'}
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};
